# CORE Applying Advanced Transformations

The Task
Your task is two-fold:

# I. Clean the files and combine them into one final DataFrame.

This dataframe should have the following columns:
- Hero (Just the name of the Hero)
- Publisher
- Gender
- Eye color
- Race
- Hair color
- Height (numeric)
- Skin color
- Alignment
- Weight (numeric)

Plus, one-hot-encoded columns for every power that appears in the dataset. E.g.:
- Agility
- Flight
- Superspeed
- etc.
    * Hint: There is a space in "100 kg" or "52.5 cm"

## Imports

In [1]:
# Standard Imports
import numpy as np
import pandas as pd
# Importing the OS and JSON Modules
import os, json

## Superhero Info DF

In [2]:
df1 = pd.read_csv('superhero_info - superhero_info.csv')
df1

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"
...,...,...,...,...,...,...,...,...
458,Yellowjacket|Marvel Comics,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}"
459,Yellowjacket II|Marvel Comics,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}"
460,Yoda|George Lucas,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}"
461,Zatanna|DC Comics,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}"
462,Zoom|DC Comics,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}"

### Hero|Publisher

In [3]:
df1[['Hero Name', 'Publisher']] = df1['Hero|Publisher'].str.split('|', expand = True)
df1 = df1.drop(columns = 'Hero|Publisher')
df1.sample(3)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero Name,Publisher
30,Female,Unknown,good,Pink,purple,Unknown,"{'Height': '165.0 cm', 'Weight': '59.0 kg'}",Ariel,Marvel Comics
98,Female,Human,good,Black,green,Unknown,"{'Height': '175.0 cm', 'Weight': '61.0 kg'}",Catwoman,DC Comics
216,Female,Human / Radiation,good,Blond,blue,Unknown,"{'Height': '168.0 cm', 'Weight': '54.0 kg'}",Invisible Woman,Marvel Comics

### Measurements

In [4]:
#change single quotes on 'Measurements'
measurements = df1.loc[0,"Measurements"]
measurements = measurements.replace("'", '"')
#checking if the measurement is working
fixed_measurements = json.loads(measurements)
fixed_measurements

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

In [5]:
df1['Measurements'] = df1['Measurements'].str.replace("'", '"')
df1['Measurements'] = df1['Measurements'].apply(json.loads)
df1['Measurements'].sample(3)

446    {'Height': '188.0 cm', 'Weight': '108.0 kg'}
237     {'Height': '191.0 cm', 'Weight': '99.0 kg'}
100     {'Height': '175.0 cm', 'Weight': '63.0 kg'}
Name: Measurements, dtype: object

In [6]:
height_weight = df1['Measurements'].apply(pd.Series)
height_weight.sample(3)

       Height    Weight
339  188.0 cm  108.0 kg
284  188.0 cm  101.0 kg
274  183.0 cm   77.0 kg

In [7]:
df1 = pd.concat((df1, height_weight), axis = 1)
df1 = df1.drop(columns = 'Measurements')
df1.sample(3)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Height,Weight
445,Male,Human,good,Brown,brown,Unknown,War Machine,Marvel Comics,185.0 cm,95.0 kg
160,Male,Human,good,Brown / White,blue,Unknown,Flash,DC Comics,180.0 cm,81.0 kg
342,Male,Unknown,bad,Brown,blue,Unknown,Rick Flag,DC Comics,185.0 cm,85.0 kg

#### Height

In [8]:
df1[['Height (cm)', 'cm']] = df1['Height'].str.split(' ', expand = True)
df1 = df1.drop(columns = 'cm')
df1['Height (cm)'] =  pd.to_numeric(df1['Height (cm)'], errors = 'coerce')
df1.sample(3)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Height,Weight,Height (cm)
422,Male,Symbiote,good,Brown,blue,Unknown,Toxin,Marvel Comics,188.0 cm,97.0 kg,188.0
379,Female,Unknown,good,Red / White,green,Unknown,Songbird,Marvel Comics,165.0 cm,65.0 kg,165.0
162,Male,Human,good,Unknown,Unknown,Unknown,Flash III,DC Comics,183.0 cm,86.0 kg,183.0

#### Weight

In [9]:
df1[['Weight (kg)', 'kg']] = df1['Weight'].str.split(' ', expand = True)
df1 = df1.drop(columns = 'kg')
df1['Weight (kg)'] =  pd.to_numeric(df1['Weight (kg)'], errors = 'coerce')
df1.sample(3)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero Name,Publisher,Height,Weight,Height (cm),Weight (kg)
7,Male,Unknown,good,Unknown,Unknown,Unknown,Agent Zero,Marvel Comics,191.0 cm,104.0 kg,191.0,104.0
298,Female,Luphomoid,bad,No Hair,blue,blue,Nebula,Marvel Comics,185.0 cm,83.0 kg,185.0,83.0
318,Female,Mutant,good,Green,green,Unknown,Polaris,Marvel Comics,170.0 cm,52.0 kg,170.0,52.0

In [10]:
df1.columns

Index(['Gender', 'Race', 'Alignment', 'Hair color', 'Eye color', 'Skin color',
       'Hero Name', 'Publisher', 'Height', 'Weight', 'Height (cm)',
       'Weight (kg)'],
      dtype='object')

In [11]:
df1 = df1[['Hero Name', 'Publisher', 'Gender', 'Race', 'Height (cm)', 
           'Weight (kg)', 'Alignment', 'Hair color', 'Eye color', 'Skin color']]
df1

,Hero Name,Publisher,Gender,Race,Height (cm),Weight (kg),Alignment,Hair color,Eye color,Skin color
0,A-Bomb,Marvel Comics,Male,Human,203.0,441.0,good,No Hair,yellow,Unknown
1,Abe Sapien,Dark Horse Comics,Male,Icthyo Sapien,191.0,65.0,good,No Hair,blue,blue
2,Abin Sur,DC Comics,Male,Ungaran,185.0,90.0,good,No Hair,blue,red
3,Abomination,Marvel Comics,Male,Human / Radiation,203.0,441.0,bad,No Hair,green,Unknown
4,Absorbing Man,Marvel Comics,Male,Human,193.0,122.0,bad,No Hair,blue,Unknown
...,...,...,...,...,...,...,...,...,...,...
458,Yellowjacket,Marvel Comics,Male,Human,183.0,83.0,good,Blond,blue,Unknown
459,Yellowjacket II,Marvel Comics,Female,Human,165.0,52.0,good,Strawberry Blond,blue,Unknown
460,Yoda,George Lucas,Male,Yoda's species,66.0,17.0,good,White,brown,green
461,Zatanna,DC Comics,Female,Human,170.0,57.0,good,Black,blue,Unknown
462,Zoom,DC Comics,Male,Unknown,185.0,81.0,bad,Brown,red,Unknown

## Superhero Powers DF
### Powers

In [47]:
df2 = pd.read_csv('superhero_powers - superhero_powers.csv')
df2.rename(columns = {'hero_names' : 'Hero Name'}, inplace = True)
df2

           Hero Name                                             Powers
0            3-D Man         Agility,Super Strength,Stamina,Super Speed
1             A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2         Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3           Abin Sur                                 Lantern Power Ring
4        Abomination  Accelerated Healing,Intelligence,Super Strengt...
..               ...                                                ...
662  Yellowjacket II                 Flight,Energy Blasts,Size Changing
663             Ymir  Cold Resistance,Durability,Longevity,Super Str...
664             Yoda  Agility,Stealth,Danger Sense,Marksmanship,Weap...
665          Zatanna  Cryokinesis,Telepathy,Magic,Fire Control,Proba...
666             Zoom  Super Speed,Intangibility,Time Travel,Time Man...

[667 rows x 2 columns]

In [48]:
powers = df2.loc[2,'Powers']
powers

'Agility,Accelerated Healing,Cold Resistance,Durability,Underwater breathing,Marksmanship,Weapons Master,Longevity,Intelligence,Super Strength,Telepathy,Stamina,Immortality,Reflexes,Enhanced Sight,Sub-Mariner'

In [49]:
df2['Power split'] = df2['Powers'].str.split(',', expand = False)
df2['Power split']

0        [Agility, Super Strength, Stamina, Super Speed]
1      [Accelerated Healing, Durability, Longevity, S...
2      [Agility, Accelerated Healing, Cold Resistance...
3                                   [Lantern Power Ring]
4      [Accelerated Healing, Intelligence, Super Stre...
                             ...
662               [Flight, Energy Blasts, Size Changing]
663    [Cold Resistance, Durability, Longevity, Super...
664    [Agility, Stealth, Danger Sense, Marksmanship,...
665    [Cryokinesis, Telepathy, Magic, Fire Control, ...
666    [Super Speed, Intangibility, Time Travel, Time...
Name: Power split, Length: 667, dtype: object

In [50]:
exploaded = df2.explode('Power split')
exploaded

,Hero Name,Powers,Power split
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Agility
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Super Strength
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Stamina
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Super Speed
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Accelerated Healing
...,...,...,...
665,Zatanna,"Cryokinesis,Telepathy,Magic,Fire Control,Proba...",Weather Control
666,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",Super Speed
666,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",Intangibility
666,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",Time Travel
666,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",Time Manipulation

In [51]:
# using drop.na so we won't have NAN in our list
cols_to_make = exploaded['Power split'].dropna().unique()
cols_to_make

array(['Agility', 'Super Strength', 'Stamina', 'Super Speed',
       'Accelerated Healing', 'Durability', 'Longevity', 'Camouflage',
       'Self-Sustenance', 'Cold Resistance', 'Underwater breathing',
       'Marksmanship', 'Weapons Master', 'Intelligence', 'Telepathy',
       'Immortality', 'Reflexes', 'Enhanced Sight', 'Sub-Mariner',
       'Lantern Power Ring', 'Invulnerability', 'Animation',
       'Super Breath', 'Dimensional Awareness', 'Flight', 'Size Changing',
       'Teleportation', 'Magic', 'Dimensional Travel',
       'Molecular Manipulation', 'Energy Manipulation', 'Power Cosmic',
       'Energy Absorption', 'Elemental Transmogrification',
       'Fire Resistance', 'Natural Armor', 'Heat Resistance',
       'Matter Absorption', 'Regeneration', 'Stealth', 'Power Suit',
       'Energy Blasts', 'Energy Beams', 'Heat Generation', 'Danger Sense',
       'Phasing', 'Force Fields', 'Hypnokinesis', 'Invisibility',
       'Enhanced Senses', 'Jump', 'Shapeshifting', 'Elasticity',
       'Substance Secretion', 'Enhanced Hearing', 'Adaptation', 'Gliding',
       'Natural Weapons', 'Wallcrawling', 'Vision - Thermal',
       'Power Augmentation', 'Cryokinesis', 'Duplication',
       'Weapon-based Powers', 'Fire Control', 'Enhanced Memory',
       'Energy Constructs', 'Power Absorption', 'Time Travel',
       'Enhanced Smell', 'Water Control', 'Vision - Telescopic',
       'Magnetism', 'Vision - Microscopic', 'Vision - Night',
       'Vision - Heat', 'Vision - X-Ray', 'Psionic Powers',
       'Toxin and Disease Resistance', 'Animal Attributes',
       'Animal Oriented Powers', 'Toxin and Disease Control', 'Empathy',
       'Animal Control', 'Darkforce Manipulation', 'Time Manipulation',
       'Reality Warping', 'Web Creation', 'Symbiote Costume',
       'Telekinesis', 'Levitation', 'Biokinesis', 'Sonar',
       'Enhanced Touch', 'Seismic Power', 'Energy Armor',
       'Omnilingualism', 'Radiation Immunity', 'Density Control',
       'Light Control', 'Illumination', 'Molecular Combustion',
       'Astral Travel', 'Precognition', 'Intangibility', 'Illusions',
       'Audio Control', 'Sonic Scream', 'Peak Human Condition',
       'Vision - Infrared', 'Dexterity', 'Omnitrix', 'Omnipotent',
       'Possession', 'Energy Resistance', 'Vision - Cryo', 'Mind Control',
       'Mind Blast', 'Clairvoyance', 'Probability Manipulation',
       'Death Touch', 'Electrokinesis', 'Gravity Control',
       'Technopath/Cyberpath', 'Radar Sense', 'Astral Projection',
       'Cloaking', 'Telepathy Resistance', 'Mind Control Resistance',
       'Hyperkinesis', 'Spatial Awareness', 'Radiation Control',
       'Radiation Absorption', 'Magic Resistance', 'Element Control',
       'Plant Control', 'Terrakinesis', 'Power Sense', 'Wind Control',
       'Qwardian Power Ring', 'Echolocation', 'Resurrection', 'The Force',
       'Summoning', 'Banish', 'Molecular Dissipation',
       'Electrical Transport', 'Speed Force', 'Grim Reaping',
       'Portal Creation', 'Vitakinesis', 'Projection', 'Insanity',
       'Photographic Reflexes', 'Anti-Gravity', 'Thirstokinesis',
       'Power Nullifier', 'Weather Control', 'Omnipresent', 'Omniscient',
       'Hair Manipulation', 'Nova Force', 'Odin Force', 'Phoenix Force',
       'Intuitive aptitude', 'Melting', 'Changing Armor'], dtype=object)

In [52]:
frames = [df2]

for col in cols_to_make:
    frame = pd.DataFrame()
    frame[col] = df2['Powers'].str.contains(col)
    frames.append(frame)
    df2 = pd.concat(frames, axis = 1)
    
df2.sample(3)

,Hero Name,Powers,Power split,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
51,Azazel,"Accelerated Healing,Longevity,Teleportation,Di...","[Accelerated Healing, Longevity, Teleportation...",False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
488,Quicksilver,"Durability,Super Strength,Super Speed,Molecula...","[Durability, Super Strength, Super Speed, Mole...",False,True,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
59,Batgirl IV,"Agility,Stealth,Weapons Master,Peak Human Cond...","[Agility, Stealth, Weapons Master, Peak Human ...",True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [53]:
df2 = df2.drop(columns = ['Powers', 'Power split',])
df2.sample(3)

,Hero Name,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,Camouflage,Self-Sustenance,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
62,Batman II,True,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
84,Bizarro-Girl,True,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
404,Meltdown,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Merging Two Dataframes

In [55]:
df = pd.merge(df1, df2, on = "Hero Name")
df.sample(3)

,Hero Name,Publisher,Gender,Race,Height (cm),Weight (kg),Alignment,Hair color,Eye color,Skin color,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
50,Beast,Marvel Comics,Male,Mutant,180.0,181.0,good,Blue,blue,blue,...,False,False,False,False,False,False,False,False,False,False
246,Lightning Lad,DC Comics,Male,Unknown,155.0,65.0,good,Red,blue,Unknown,...,False,False,False,False,False,False,False,False,False,False
84,Buffy,Dark Horse Comics,Female,Human,157.0,52.0,good,Blond,green,Unknown,...,False,False,False,False,False,False,False,False,False,False

# II. Use your combined DataFrame to answer the following questions.

In [56]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 463 entries, 0 to 462
Columns: 177 entries, Hero Name to Changing Armor
dtypes: bool(167), float64(2), object(8)
memory usage: 115.3+ KB

,Hero Name,Publisher,Gender,Race,Height (cm),Weight (kg),Alignment,Hair color,Eye color,Skin color,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,A-Bomb,Marvel Comics,Male,Human,203.0,441.0,good,No Hair,yellow,Unknown,...,False,False,False,False,False,False,False,False,False,False
1,Abe Sapien,Dark Horse Comics,Male,Icthyo Sapien,191.0,65.0,good,No Hair,blue,blue,...,False,False,False,False,False,False,False,False,False,False
2,Abin Sur,DC Comics,Male,Ungaran,185.0,90.0,good,No Hair,blue,red,...,False,False,False,False,False,False,False,False,False,False
3,Abomination,Marvel Comics,Male,Human / Radiation,203.0,441.0,bad,No Hair,green,Unknown,...,False,False,False,False,False,False,False,False,False,False
4,Absorbing Man,Marvel Comics,Male,Human,193.0,122.0,bad,No Hair,blue,Unknown,...,False,False,False,False,False,False,False,False,False,False

In [57]:
# making sure that the Height and Weight columns are the float types
df.dtypes[df.dtypes == 'float']

Height (cm)    float64
Weight (kg)    float64
dtype: object

1. Compare the average weight of super powers who have Super Speed to those who do not.

In [58]:
speed_mean = (df.groupby('Super Speed')['Weight (kg)'].mean()).round(2).sort_values(ascending = False)
speed_mean

Super Speed
True     129.40
False    101.77
Name: Weight (kg), dtype: float64

2. What is the average height of heroes for each publisher?

In [59]:
height_mean = (df.groupby('Publisher')['Height (cm)'].mean()).round(2).sort_values(ascending = False)
height_mean

Publisher
Image Comics         211.00
Marvel Comics        191.55
DC Comics            181.92
Star Trek            181.50
Team Epic TV         180.75
Unknown              178.00
Dark Horse Comics    176.91
Shueisha             171.50
George Lucas         159.60
Name: Height (cm), dtype: float64